from typing import Dict

from app.graph.state import PlayerState

# 预设角色卡模板库
# 使用硬编码字典用于基础测试和快速起步，对应 state.PlayerState 结构
PREDEFINED_CHARACTERS: Dict[str, dict] = {
    "战士": {
        "name": "预设-战士",
        "role_class": "战士",
        "level": 1,
        "hp": 12,
        "max_hp": 12,
        "temp_hp": 0,
        "base_ac": 16,
        "ac": 16,
        "xp": 0,
        "abilities": {
            "str": 16,
            "dex": 14,
            "con": 15,
            "int": 10,
            "wis": 12,
            "cha": 8,
        },
        "modifiers": {
            "str": 3,
            "dex": 2,
            "con": 2,
            "int": 0,
            "wis": 1,
            "cha": -1,
        },
        "conditions": [],
        "resources": {"second_wind_uses": 1},
        "resource_caps": {"second_wind_uses": 1},
        "known_spells": [],
        "class_features": ["fighting_style", "second_wind"],
        "spellcasting_ability": "",
        "fighting_style": "",
        "fighter_archetype": "",
        "weapons": [
            {"name": "Longsword", "damage_dice": "1d8", "damage_type": "slashing", "weapon_type": "melee", "properties": ["versatile"]},
            {"name": "Handaxe", "damage_dice": "1d6", "damage_type": "slashing", "weapon_type": "melee", "properties": ["light", "thrown"]},
        ],
    },
    "法师": {
        "name": "预设-法师",
        "role_class": "法师",
        "level": 1,
        "hp": 8,
        "max_hp": 8,
        "temp_hp": 0,
        "base_ac": 12,
        "ac": 12,
        "xp": 0,
        "abilities": {
            "str": 8,
            "dex": 14,
            "con": 14,
            "int": 16,
            "wis": 12,
            "cha": 10,
        },
        "modifiers": {
            "str": -1,
            "dex": 2,
            "con": 2,
            "int": 3,
            "wis": 1,
            "cha": 0,
        },
        "conditions": [],
        "resources": {"spell_slot_lv1": 2},
        "resource_caps": {"spell_slot_lv1": 2},
        "known_spells": ["magic_missile", "mage_armor"],
        "known_cantrips": ["fire_bolt", "toll_the_dead", "ray_of_frost"],
        "class_features": [],
        "spellcasting_ability": "int",
        "arcane_tradition": "",
        "weapons": [
            {"name": "Dagger", "damage_dice": "1d4", "damage_type": "piercing", "weapon_type": "melee", "properties": ["finesse", "light", "thrown"]},
        ],
    },
    "游荡者": {
        "name": "预设-游荡者",
        "role_class": "游荡者",
        "level": 1,
        "hp": 10,
        "max_hp": 10,
        "temp_hp": 0,
        "base_ac": 14,
        "ac": 14,
        "abilities": {
            "str": 10,
            "dex": 16,
            "con": 14,
            "int": 12,
            "wis": 10,
            "cha": 14,
        },
        "modifiers": {
            "str": 0,
            "dex": 3,
            "con": 2,
            "int": 1,
            "wis": 0,
            "cha": 2,
        },
        "conditions": [],
        "resources": {},
        "known_spells": [],
        "class_features": [],
        "spellcasting_ability": "",
        "weapons": [
            {"name": "Shortsword", "damage_dice": "1d6", "damage_type": "piercing", "weapon_type": "melee", "properties": ["finesse", "light"]},
            {"name": "Shortbow", "damage_dice": "1d6", "damage_type": "piercing", "weapon_type": "ranged", "properties": []},
        ],
    },
    "牧师": {
        "name": "预设-牧师",
        "role_class": "牧师",
        "level": 1,
        "hp": 10,
        "max_hp": 10,
        "temp_hp": 0,
        "base_ac": 14,
        "ac": 14,
        "abilities": {
            "str": 12,
            "dex": 12,
            "con": 14,
            "int": 12,
            "wis": 16,
            "cha": 13,
        },
        "modifiers": {
            "str": 1,
            "dex": 1,
            "con": 2,
            "int": 1,
            "wis": 3,
            "cha": 1,
        },
        "conditions": [],
        "resources": {"spell_slot_lv1": 2},
        "known_spells": ["cure_wounds"],
        "known_cantrips": ["fire_bolt", "toll_the_dead", "ray_of_frost"],
        "class_features": [],
        "spellcasting_ability": "wis",
        "weapons": [
            {"name": "Mace", "damage_dice": "1d6", "damage_type": "bludgeoning", "weapon_type": "melee", "properties": []},
        ],
    },
    "术士": {
        "name": "预设-术士",
        "role_class": "术士",
        "level": 1,
        "hp": 8,
        "max_hp": 8,
        "temp_hp": 0,
        "base_ac": 13,
        "ac": 13,
        "abilities": {
            "str": 8,
            "dex": 14,
            "con": 15,
            "int": 12,
            "wis": 10,
            "cha": 17,
        },
        "modifiers": {
            "str": -1,
            "dex": 2,
            "con": 2,
            "int": 1,
            "wis": 0,
            "cha": 3,
        },
        "conditions": [],
        "resources": {"spell_slot_lv1": 2},
        "known_spells": ["magic_missile", "mage_armor", "burning_hands", "shield"],
        "known_cantrips": ["fire_bolt", "toll_the_dead", "ray_of_frost"],
        "class_features": [],
        "spellcasting_ability": "cha",
        "weapons": [
            {"name": "Dagger", "damage_dice": "1d4", "damage_type": "piercing", "weapon_type": "melee", "properties": ["finesse", "light", "thrown"]},
        ],
    },
    "游侠": {
        "name": "预设-游侠",
        "role_class": "游侠",
        "level": 1,
        "hp": 12,
        "max_hp": 12,
        "temp_hp": 0,
        "base_ac": 14,
        "ac": 14,
        "abilities": {
            "str": 14,
            "dex": 16,
            "con": 14,
            "int": 10,
            "wis": 15,
            "cha": 12,
        },
        "modifiers": {
            "str": 2,
            "dex": 3,
            "con": 2,
            "int": 0,
            "wis": 2,
            "cha": 1,
        },
        "conditions": [],
        "resources": {"spell_slot_lv1": 1},
        "known_spells": ["cure_wounds"],
        "known_cantrips": ["fire_bolt", "toll_the_dead", "ray_of_frost"],
        "class_features": [],
        "spellcasting_ability": "wis",
        "weapons": [
            {"name": "Shortsword", "damage_dice": "1d6", "damage_type": "piercing", "weapon_type": "melee", "properties": ["finesse", "light"]},
            {"name": "Longbow", "damage_dice": "1d8", "damage_type": "piercing", "weapon_type": "ranged", "properties": []},
        ],
    },
    "武僧": {
        "name": "预设-武僧",
        "role_class": "武僧",
        "level": 1,
        "hp": 10,
        "max_hp": 10,
        "temp_hp": 0,
        "base_ac": 15,
        "ac": 15,
        "abilities": {
            "str": 14,
            "dex": 16,
            "con": 14,
            "int": 10,
            "wis": 15,
            "cha": 12,
        },
        "modifiers": {
            "str": 2,
            "dex": 3,
            "con": 2,
            "int": 0,
            "wis": 2,
            "cha": 1,
        },
        "conditions": [],
        "resources": {"ki_points": 2},
        "known_spells": [],
        "class_features": [],
        "spellcasting_ability": "",
        "weapons": [
            {"name": "Shortsword", "damage_dice": "1d6", "damage_type": "piercing", "weapon_type": "melee", "properties": ["finesse", "light"]},
        ],
    },
    "圣武士": {
        "name": "预设-圣武士",
        "role_class": "圣武士",
        "level": 1,
        "hp": 12,
        "max_hp": 12,
        "temp_hp": 0,
        "base_ac": 16,
        "ac": 16,
        "abilities": {
            "str": 16,
            "dex": 10,
            "con": 14,
            "int": 10,
            "wis": 13,
            "cha": 15,
        },
        "modifiers": {
            "str": 3,
            "dex": 0,
            "con": 2,
            "int": 0,
            "wis": 1,
            "cha": 2,
        },
        "conditions": [],
        "resources": {"spell_slot_lv1": 0},
        "known_spells": [],
        "known_cantrips": ["fire_bolt", "toll_the_dead", "ray_of_frost"],
        "class_features": [],
        "spellcasting_ability": "cha",
        "weapons": [
            {"name": "Longsword", "damage_dice": "1d8", "damage_type": "slashing", "weapon_type": "melee", "properties": ["versatile"]},
        ],
    },
    "邪术师": {
        "name": "预设-邪术师",
        "role_class": "邪术师",
        "level": 1,
        "hp": 9,
        "max_hp": 9,
        "temp_hp": 0,
        "base_ac": 12,
        "ac": 12,
        "abilities": {
            "str": 8,
            "dex": 14,
            "con": 13,
            "int": 12,
            "wis": 10,
            "cha": 16,
        },
        "modifiers": {
            "str": -1,
            "dex": 2,
            "con": 1,
            "int": 1,
            "wis": 0,
            "cha": 3,
        },
        "conditions": [],
        "resources": {"pact_magic_lv1": 1},
        "known_spells": ["burning_hands"],
        "known_cantrips": ["fire_bolt", "toll_the_dead", "ray_of_frost"],
        "class_features": [],
        "spellcasting_ability": "cha",
        "weapons": [
            {"name": "Dagger", "damage_dice": "1d4", "damage_type": "piercing", "weapon_type": "melee", "properties": ["finesse", "light", "thrown"]},
        ],
    },
    "德鲁伊": {
        "name": "预设-德鲁伊",
        "role_class": "德鲁伊",
        "level": 1,
        "hp": 10,
        "max_hp": 10,
        "temp_hp": 0,
        "base_ac": 13,
        "ac": 13,
        "abilities": {
            "str": 10,
            "dex": 14,
            "con": 14,
            "int": 12,
            "wis": 16,
            "cha": 13,
        },
        "modifiers": {
            "str": 0,
            "dex": 2,
            "con": 2,
            "int": 1,
            "wis": 3,
            "cha": 1,
        },
        "conditions": [],
        "resources": {"spell_slot_lv1": 2},
        "known_spells": ["cure_wounds", "burning_hands", "ice_knife"],
        "known_cantrips": ["fire_bolt", "toll_the_dead", "ray_of_frost"],
        "class_features": [],
        "spellcasting_ability": "wis",
        "weapons": [
            {"name": "Scimitar", "damage_dice": "1d6", "damage_type": "slashing", "weapon_type": "melee", "properties": ["finesse", "light"]},
        ],
    },
    "吟游诗人": {
        "name": "预设-吟游诗人",
        "role_class": "吟游诗人",
        "level": 1,
        "hp": 9,
        "max_hp": 9,
        "temp_hp": 0,
        "base_ac": 14,
        "ac": 14,
        "abilities": {
            "str": 8,
            "dex": 14,
            "con": 13,
            "int": 12,
            "wis": 10,
            "cha": 16,
        },
        "modifiers": {
            "str": -1,
            "dex": 2,
            "con": 1,
            "int": 1,
            "wis": 0,
            "cha": 3,
        },
        "conditions": [],
        "resources": {"spell_slot_lv1": 2},
        "known_spells": ["cure_wounds"],
        "known_cantrips": ["fire_bolt", "toll_the_dead", "ray_of_frost"],
        "class_features": [],
        "spellcasting_ability": "cha",
        "weapons": [
            {"name": "Rapier", "damage_dice": "1d8", "damage_type": "piercing", "weapon_type": "melee", "properties": ["finesse"]},
        ],
    },
    "野蛮人": {
        "name": "预设-野蛮人",
        "role_class": "野蛮人",
        "level": 1,
        "hp": 15,
        "max_hp": 15,
        "temp_hp": 0,
        "base_ac": 14,
        "ac": 14,
        "abilities": {
            "str": 16,
            "dex": 12,
            "con": 16,
            "int": 8,
            "wis": 13,
            "cha": 10,
        },
        "modifiers": {
            "str": 3,
            "dex": 1,
            "con": 3,
            "int": -1,
            "wis": 1,
            "cha": 0,
        },
        "conditions": [],
        "resources": {"rage_uses": 2},
        "known_spells": [],
        "class_features": [],
        "spellcasting_ability": "",
        "weapons": [
            {"name": "Greataxe", "damage_dice": "1d12", "damage_type": "slashing", "weapon_type": "melee", "properties": ["heavy", "two-handed"]},
            {"name": "Javelin", "damage_dice": "1d6", "damage_type": "piercing", "weapon_type": "melee", "properties": ["thrown"]},
        ],
    },
}
